---
fixtures:
  repositories:
    pam: https://github.com/simp/pupmod-simp-pam
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
  symlinks:
    libvirt_backups: "#{source_dir}"
